[package]
name = "glyph_parser"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/font",
    "crates/rasterizer",
]

[dependencies]
font = { path = "crates/font" }
rasterizer = { path = "crates/rasterizer" }
byteorder = "1.4"
